apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  setting: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-krust
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-krust
  template:
    metadata:
      labels:
        app: hello-krust
    spec:
      containers:
      - name: app
        image: krust://./example/hello-krust
      initContainers:
      - name: init
        image: krust://./example/hello-krust
---
apiVersion: v1
kind: Service
metadata:
  name: hello-krust-svc
spec:
  selector:
    app: hello-krust
  ports:
  - port: 80
    targetPort: 8080
